### ISSUE TITLE
BUG SURVIVANT

### ISSUE THREAD

**Issue by SkiiZ-Switch** [SkiiZ-Switch/OLoupGarou#6]
[LoupGarou] Task #670 for LoupGarou v1.10.0 generated an exception
java.lang.NullPointerException: null
        at fr.leomelki.loupgarou.roles.RSurvivant.openInventory(RSurvivant.java:95) ~[?:?]
        at fr.leomelki.loupgarou.roles.RSurvivant.onNightTurn(RSurvivant.java:131) ~[?:?]
        at fr.leomelki.loupgarou.roles.Role$1.run(Role.java:93) ~[?:?]
        at fr.leomelki.loupgarou.roles.Role.onNightTurn(Role.java:109) ~[?:?]
        at fr.leomelki.loupgarou.classes.LGGame$7$1.run(LGGame.java:551) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by SkiiZ-Switch** [comment]
Le bug venait de la fonction join, le override n'était pas fait sur la bonne signature,
J'ai donc changer l'override et j'ai modifier la façon de gérer la variable de cache
